In [1]:
import json
import string
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
data_one = []
reviewdata_df = []

In [3]:
data_file = open('F:\yelp\yelp_academic_dataset_review.json')
length = 2225213  # I calculated length prior to this calculation
for i, line in enumerate(data_file):
    if i<(length/4):
        data_one.append(json.loads(line))
data_file.close()

In [4]:
df = pd.DataFrame(data_one)

In [5]:
data_main = []
with open('F:\yelp\yelp_academic_dataset_user.json') as f:
    for line in f:
        data_main.append(json.loads(line))

In [6]:
df_user = pd.DataFrame(data_main)

In [7]:
def user_with_friends(x):
    if len(x['friends']) != 0:
        return x

In [8]:
df_user_with_friends = df_user.apply(user_with_friends, axis=1)

In [9]:
df_user_with_friends = df_user_with_friends.dropna()

In [10]:
def elite_users(x):
    if len(x['elite']) != 0:
        return x

In [11]:
df_elite_users = df_user_with_friends.apply(elite_users, axis=1)

In [15]:
df_elite_users = df_elite_users.dropna()

In [14]:
df_elite_users.head(n=10)

,average_stars,compliments,elite,fans,friends,name,review_count,type,user_id,votes,yelping_since
0,4.14,"{u'profile': 8, u'cute': 15, u'funny': 11, u'p...","[2005, 2006]",70,"[rpOyqD_893cqmDAtJLbdog, 4U9kSBLuBDU391x6bxU-Y...",Russel,108,user,18kPq7GPye-YQ3LyKyAZPw,"{u'funny': 167, u'useful': 280, u'cool': 245}",2004-10
1,3.66,"{u'profile': 116, u'cute': 206, u'funny': 580,...","[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",1179,"[18kPq7GPye-YQ3LyKyAZPw, 4U9kSBLuBDU391x6bxU-Y...",Jeremy,1274,user,rpOyqD_893cqmDAtJLbdog,"{u'funny': 7681, u'useful': 14199, u'cool': 11...",2004-10
2,3.60,"{u'profile': 9, u'cute': 23, u'funny': 120, u'...","[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",100,"[18kPq7GPye-YQ3LyKyAZPw, rpOyqD_893cqmDAtJLbdo...",Michael,442,user,4U9kSBLuBDU391x6bxU-YA,"{u'funny': 908, u'useful': 1483, u'cool': 732}",2004-10
4,3.80,"{u'cute': 2, u'plain': 2, u'writer': 2, u'note...",[2005],4,"[rpOyqD_893cqmDAtJLbdog, HDQixQ-WZEV0LVPJlIGQe...",Katherine,66,user,SIBCL7HBkrP4llolm4SC2A,"{u'funny': 11, u'useful': 34, u'cool': 13}",2004-10
5,4.35,"{u'profile': 231, u'cute': 274, u'funny': 1507...","[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",807,"[18kPq7GPye-YQ3LyKyAZPw, rpOyqD_893cqmDAtJLbdo...",Joan,1611,user,8J4IIYcqBlFch8T90N923A,"{u'funny': 13010, u'useful': 17705, u'cool': 1...",2004-10
6,4.45,"{u'profile': 2, u'cute': 4, u'funny': 2, u'pla...","[2005, 2006, 2007]",6,"[rpOyqD_893cqmDAtJLbdog, 4U9kSBLuBDU391x6bxU-Y...",George,55,user,ysYmC-ufbdmVEX9yAv-VEQ,"{u'funny': 35, u'useful': 39, u'cool': 25}",2004-10
7,3.88,"{u'plain': 5, u'hot': 1, u'cool': 1}",[2005],2,"[i63u3SdbrLsP4FxiSKP0Zw, lGrDfsaWl9IDUcEeUWyn6A]",Mary,60,user,WPOKvkacSKHx_bIG1alFiA,"{u'funny': 32, u'useful': 131, u'cool': 34}",2004-10
10,4.02,"{u'profile': 9, u'cute': 82, u'funny': 70, u'p...","[2005, 2006, 2007, 2008, 2010, 2011, 2012]",78,"[XejvgD4CrkR7FeIkjwAjtQ, T7t5UdadpHua-YnmiFpcZ...",Helen,983,user,ZWOj6LmzwGvMDh-A85EOtA,"{u'funny': 1109, u'useful': 2404, u'cool': 1928}",2004-10
12,4.05,"{u'cute': 1, u'funny': 1, u'plain': 6, u'write...","[2012, 2013, 2014, 2015]",7,"[23bCUONbJfIrtsLgX7Dgvg, l1eXX3p2WL_02FWw5TXhs...",Steven,362,user,za5Q2uYrTmky9w_3h9k_wQ,"{u'funny': 60, u'useful': 255, u'cool': 77}",2008-11
17,3.71,"{u'profile': 1, u'cute': 2, u'funny': 4, u'pla...","[2011, 2012, 2013]",2,"[Q9n39MgkWbvf6ohzQCDO7Q, xynvN_YDNcqJjpqtRGgr5...",edwin,72,user,4mk28YCp7kCKI6WUp3Gl7w,"{u'funny': 112, u'useful': 231, u'cool': 165}",2008-11

In [10]:
df_user.shape

(552339, 11)

In [17]:
df_user_with_friends.head(n=15)

,average_stars,compliments,elite,fans,friends,name,review_count,type,user_id,votes,yelping_since
0,4.14,"{u'profile': 8, u'cute': 15, u'funny': 11, u'p...","[2005, 2006]",70,"[rpOyqD_893cqmDAtJLbdog, 4U9kSBLuBDU391x6bxU-Y...",Russel,108,user,18kPq7GPye-YQ3LyKyAZPw,"{u'funny': 167, u'useful': 280, u'cool': 245}",2004-10
1,3.66,"{u'profile': 116, u'cute': 206, u'funny': 580,...","[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",1179,"[18kPq7GPye-YQ3LyKyAZPw, 4U9kSBLuBDU391x6bxU-Y...",Jeremy,1274,user,rpOyqD_893cqmDAtJLbdog,"{u'funny': 7681, u'useful': 14199, u'cool': 11...",2004-10
2,3.60,"{u'profile': 9, u'cute': 23, u'funny': 120, u'...","[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",100,"[18kPq7GPye-YQ3LyKyAZPw, rpOyqD_893cqmDAtJLbdo...",Michael,442,user,4U9kSBLuBDU391x6bxU-YA,"{u'funny': 908, u'useful': 1483, u'cool': 732}",2004-10
3,4.64,{u'cute': 2},[],2,"[18kPq7GPye-YQ3LyKyAZPw, rpOyqD_893cqmDAtJLbdo...",Ken,11,user,fHtTaujcyKvXglE33Z5yIw,"{u'funny': 1, u'useful': 11, u'cool': 5}",2004-10
4,3.80,"{u'cute': 2, u'plain': 2, u'writer': 2, u'note...",[2005],4,"[rpOyqD_893cqmDAtJLbdog, HDQixQ-WZEV0LVPJlIGQe...",Katherine,66,user,SIBCL7HBkrP4llolm4SC2A,"{u'funny': 11, u'useful': 34, u'cool': 13}",2004-10
5,4.35,"{u'profile': 231, u'cute': 274, u'funny': 1507...","[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",807,"[18kPq7GPye-YQ3LyKyAZPw, rpOyqD_893cqmDAtJLbdo...",Joan,1611,user,8J4IIYcqBlFch8T90N923A,"{u'funny': 13010, u'useful': 17705, u'cool': 1...",2004-10
6,4.45,"{u'profile': 2, u'cute': 4, u'funny': 2, u'pla...","[2005, 2006, 2007]",6,"[rpOyqD_893cqmDAtJLbdog, 4U9kSBLuBDU391x6bxU-Y...",George,55,user,ysYmC-ufbdmVEX9yAv-VEQ,"{u'funny': 35, u'useful': 39, u'cool': 25}",2004-10
7,3.88,"{u'plain': 5, u'hot': 1, u'cool': 1}",[2005],2,"[i63u3SdbrLsP4FxiSKP0Zw, lGrDfsaWl9IDUcEeUWyn6A]",Mary,60,user,WPOKvkacSKHx_bIG1alFiA,"{u'funny': 32, u'useful': 131, u'cool': 34}",2004-10
8,3.58,"{u'profile': 1, u'cute': 1, u'funny': 8, u'pla...",[],7,"[rpOyqD_893cqmDAtJLbdog, 4U9kSBLuBDU391x6bxU-Y...",Nader,101,user,UTS9XcT14H2ZscRIf0MYHQ,"{u'funny': 53, u'useful': 243, u'cool': 49}",2004-10
9,4.30,"{u'photos': 1, u'hot': 1, u'plain': 2, u'cool'...",[],0,"[4U9kSBLuBDU391x6bxU-YA, PMgE5Yqv7QL_cTjjInyYI...",Joseph,20,user,qL7Astun3i7qwr2IL5iowA,"{u'funny': 6, u'useful': 30, u'cool': 15}",2004-10
10,4.02,"{u'profile': 9, u'cute': 82, u'funny': 70, u'p...","[2005, 2006, 2007, 2008, 2010, 2011, 2012]",78,"[XejvgD4CrkR7FeIkjwAjtQ, T7t5UdadpHua-YnmiFpcZ...",Helen,983,user,ZWOj6LmzwGvMDh-A85EOtA,"{u'funny': 1109, u'useful': 2404, u'cool': 1928}",2004-10
11,3.82,"{u'cute': 2, u'funny': 1, u'plain': 1, u'write...",[],8,"[18kPq7GPye-YQ3LyKyAZPw, rpOyqD_893cqmDAtJLbdo...",Yishan,45,user,HDQixQ-WZEV0LVPJlIGQeQ,"{u'funny': 44, u'useful': 48, u'cool': 19}",2004-10
12,4.05,"{u'cute': 1, u'funny': 1, u'plain': 6, u'write...","[2012, 2013, 2014, 2015]",7,"[23bCUONbJfIrtsLgX7Dgvg, l1eXX3p2WL_02FWw5TXhs...",Steven,362,user,za5Q2uYrTmky9w_3h9k_wQ,"{u'funny': 60, u'useful': 255, u'cool': 77}",2008-11
14,4.18,"{u'funny': 1, u'writer': 1}",[],0,"[qy5Fas6mjr1Q6GaNf2d-oQ, WUq9lsaYAEzpsXvFjOM-d...",J,10,user,HZJ9qzZlXC8xeC8v7VT8WA,"{u'funny': 1, u'useful': 12, u'cool': 6}",2008-11
15,4.00,{u'cool': 1},[],0,[IdTEv_KFct0KU3Cd550nEw],Joe,7,user,y6tOSRh3Xng3XKjVFoE2qw,"{u'funny': 0, u'useful': 5, u'cool': 1}",2008-11

In [18]:
merged_df = pd.merge(df, df_user_with_friends, on='user_id', how='inner')

In [19]:
merged_df.head(n=1)

,business_id,date,review_id,stars,text,type_x,user_id,votes_x,average_stars,compliments,elite,fans,friends,name,review_count,type_y,votes_y,yelping_since
0,UsFtqoBl7naz8AVUBZMjQQ,2013-11-08,Di3exaUCFNw1V4kSNW5pgA,5,All the food is great here. But the best thing...,review,uK8tzraOp4M5u3uYrqIBXg,"{u'funny': 0, u'useful': 0, u'cool': 0}",3.84,{},[],2,"[53wSMIztehsjP-vJZBS54A, CXhOU5apSRSTtEUiyoqH3Q]",Robin,46,user,"{u'funny': 2, u'useful': 36, u'cool': 5}",2013-05

In [20]:
merged_df.shape

(394815, 18)

In [21]:
merged_df.stars.value_counts(ascending=True)

2     36085
1     38347
3     63586
4    124241
5    132556
Name: stars, dtype: int64

In [22]:
data_business = []
with open('F:\yelp\yelp_academic_dataset_business.json') as f:
    for line in f:
        data_business.append(json.loads(line))

In [23]:
df_business = pd.DataFrame(data_business)

In [24]:
business_merged_df = pd.merge(merged_df, df_business, on='business_id', how='inner')

In [25]:
business_merged_df.shape

(394815, 32)

In [26]:
business_merged_df.drop(['neighborhoods', 'latitude', 'longitude', 'yelping_since', 'compliments', 'full_address', 'city', 'state',
                         'open', 'hours', 'attributes'], axis=1, inplace=True)

In [27]:
business_merged_df.head(n=1)

,business_id,date,review_id,stars_x,text,type_x,user_id,votes_x,average_stars,elite,...,friends,name_x,review_count_x,type_y,votes_y,categories,name_y,review_count_y,stars_y,type
0,UsFtqoBl7naz8AVUBZMjQQ,2013-11-08,Di3exaUCFNw1V4kSNW5pgA,5,All the food is great here. But the best thing...,review,uK8tzraOp4M5u3uYrqIBXg,"{u'funny': 0, u'useful': 0, u'cool': 0}",3.84,[],...,"[53wSMIztehsjP-vJZBS54A, CXhOU5apSRSTtEUiyoqH3Q]",Robin,46,user,"{u'funny': 2, u'useful': 36, u'cool': 5}",[Nightlife],Clancy's Pub,4,3.5,business

In [28]:
business_merged_df = business_merged_df.loc[business_merged_df.categories.apply(lambda cat: 'Food' in cat or 'Restaurants' in cat)]

In [29]:
business_merged_df.shape

(252836, 21)

In [30]:
grouped = business_merged_df.groupby(business_merged_df['business_id'])

In [31]:
def look_for_user_ratings1(group, biz_id):
    ur = []
    for row in group.itertuples():
        ur.append({
                "user_id": row[7],
                "user_rating": row[4],
            })
    return ur

In [32]:
business_user1 = {}
li = []
for business_id, group in grouped:
    business_user1.update({
        business_id: look_for_user_ratings1(group, business_id)
    })

In [33]:
print business_user1.get('PSAK5sUss8yiN7Q_72Zlxw')

[{'user_rating': 5, 'user_id': u'F6QsMoJdvtohlbnST-fDyQ'}, {'user_rating': 3, 'user_id': u'wuCszpVPMIMyOCualnZtaw'}, {'user_rating': 2, 'user_id': u'pQ6ij6cOBRB3yJGHbVZHUQ'}, {'user_rating': 4, 'user_id': u'MNfOCJZsbtMbnDlvJ1LKeQ'}, {'user_rating': 5, 'user_id': u'_LsbT_uW0UE6rhsWiAIrsg'}, {'user_rating': 3, 'user_id': u'ND95DgvN7ba8MabfXE3lsw'}, {'user_rating': 3, 'user_id': u'qeljTFFJaZE-HJ6RKx0iFg'}, {'user_rating': 4, 'user_id': u'HxZ6tI_7G1ssxlZGV6dByA'}]

In [34]:
##This is the 2nd hashmap

user_friends = {}

for row in df_user_with_friends.itertuples():
    user_id = row[9]
#    print user_id
    user_friends.update({
        user_id: row[5],
    })

In [35]:
def look_for_business_ratings(business_user_dict, business_id, user_ids):
    ratings = business_user_dict.get(business_id)
    sum_of_stars = 0
    count = 0
    business_reviewers = [li['user_id'] for li in ratings]
    for i, uid in enumerate(business_reviewers):
        for user in user_ids:
            if uid == user:
                count += 1
                sum_of_stars += ratings[i]['user_rating']
    avg = float(sum_of_stars/float(count))
    return avg

In [50]:
new_df = []

for row in business_merged_df.head(n=200).itertuples():
    business_id = row[1]
    user_id = row[7]
    ratings = business_user1.get(business_id)
    
    friends = user_friends.get(user_id)
    business_reviewers = [li['user_id'] for li in ratings]

    elite_users = []
    for user in business_reviewers:
        if df_elite_users[df_elite_users['user_id'] == user].empty:
            elite_users.append(user)
    
#     for user in business_reviewers:
# #         print df_user_with_friends[df_user_with_friends['user_id'] == user].index.tolist()
# #        print df_user_with_friends.loc[df_user_with_friends[df_user_with_friends['user_id'] == user].index]
#         idx = df_user_with_friends[df_user_with_friends['user_id'] == user].index.tolist()
#         print df_user_with_friends.loc[idx]['elite']
#         print len(df_user_with_friends.loc[idx]['elite'])
#            print "yes"
            #elite_users.append(df_user_with_friends.loc[idx]['user_id'])
            
#    print elite_users
#            print index
#         if user in df_user_with_friends['user_id']:
#             print df_user_with_friends['elite']

#             print df_user_with_friends[df_user_with_friends['elite'] is not None].index.tolist()
#                 idx = df_user_with_friends[df_user_with_friends['elite'] is not None].index
#                 elite_users.append(idx)
#     print elite_users

#     for user in business_reviewers:
#         for index in df_user_with_friends[df_user_with_friends['user_id'] == user].index.tolist():
#             print df_user_with_friends.loc[index]
            
    common_reviewers = list(set(friends) & set(business_reviewers))
    if len(common_reviewers) == 0:
        continue
    else:
        friends_avg = look_for_business_ratings(business_user1, business_id, common_reviewers)
        
    new_df.append({
            "Business_id": business_id,
            "User_id": user_id,
            "friends_avg_rating": friends_avg,
            "user_rating": row[4],
            "friends_who_rated": len(common_reviewers),
            "friends": len(friends),
            "no_of_reviewers": len(business_reviewers),
            "business_rating": row[20],
            "no_elite_reviewers": len(elite_users)
        })

final_df = pd.DataFrame(new_df)

In [51]:
final_df

,Business_id,User_id,business_rating,friends,friends_avg_rating,friends_who_rated,no_elite_reviewers,no_of_reviewers,user_rating
0,mVHrayjG3uZ_RLHkLj-AMg,8fApIAMHn2MZJFUiCQto5Q,5,2,5.000000,1,8,9,5
1,mVHrayjG3uZ_RLHkLj-AMg,tAKjY3bQXH51msJbOHYPmQ,5,31,5.000000,1,8,9,5
2,YssP-_6iP0SLBsqUQGs6rQ,nEYPahVwXGD2Pjvgkm7QqQ,4,1444,4.000000,22,37,59,5
3,YssP-_6iP0SLBsqUQGs6rQ,GYNfjDbSlpdRK2qC8RqatA,4,45,4.000000,3,37,59,1
4,YssP-_6iP0SLBsqUQGs6rQ,r_96n9O0jNzbNCZDkSB0EQ,4,6,4.000000,1,37,59,5
5,YssP-_6iP0SLBsqUQGs6rQ,Enzdhh-rV5JgC4lgg0IdFw,4,149,3.333333,3,37,59,3
6,YssP-_6iP0SLBsqUQGs6rQ,ytgLwKzD6B4af5vW56RpJg,4,2,5.000000,1,37,59,5
7,YssP-_6iP0SLBsqUQGs6rQ,gtJJBaQwTwE45NnNF0coVA,4,64,4.333333,3,37,59,5
8,YssP-_6iP0SLBsqUQGs6rQ,vFgVosI6MUPX8Y23hmuMXw,4,5,5.000000,1,37,59,5
9,YssP-_6iP0SLBsqUQGs6rQ,RxEegiMllenlyhYgJqsTSQ,4,16,5.000000,1,37,59,4
10,YssP-_6iP0SLBsqUQGs6rQ,iTmWHtltCtk0Gm55AOxrUA,4,93,5.000000,2,37,59,4
11,YssP-_6iP0SLBsqUQGs6rQ,sPQ10u9ZsrCVCKhQylFxgQ,4,89,4.428571,4,37,59,2
12,YssP-_6iP0SLBsqUQGs6rQ,gwnVSev8aNLvMArs3WTfFw,4,285,4.000000,3,37,59,5
13,YssP-_6iP0SLBsqUQGs6rQ,gwnVSev8aNLvMArs3WTfFw,4,285,4.000000,3,37,59,5
14,YssP-_6iP0SLBsqUQGs6rQ,gwnVSev8aNLvMArs3WTfFw,4,285,4.000000,3,37,59,4
15,YssP-_6iP0SLBsqUQGs6rQ,gwnVSev8aNLvMArs3WTfFw,4,285,4.000000,3,37,59,5
16,YssP-_6iP0SLBsqUQGs6rQ,11Ydte1VfE85UHK24d4QRQ,4,41,4.000000,4,37,59,4
17,YssP-_6iP0SLBsqUQGs6rQ,sApvvvnEp4Z-4do3a1pDgg,4,29,5.000000,1,37,59,4
18,YssP-_6iP0SLBsqUQGs6rQ,sApvvvnEp4Z-4do3a1pDgg,4,29,5.000000,1,37,59,4
19,YssP-_6iP0SLBsqUQGs6rQ,cEN-lL4MQfmUYLJ4K1tU6g,4,14,4.000000,3,37,59,4
20,YssP-_6iP0SLBsqUQGs6rQ,wNtyBJa_qaRYUew_TWplgw,4,16,3.000000,1,37,59,3
21,YssP-_6iP0SLBsqUQGs6rQ,UFr-WCtnNbX8O3sI7h4qeQ,4,174,4.571429,4,37,59,5
22,YssP-_6iP0SLBsqUQGs6rQ,-0itF0VWVBe3k2AdfUReGA,4,44,3.000000,2,37,59,3
23,YssP-_6iP0SLBsqUQGs6rQ,rxYocLcwFsrHYOYwtHSv8g,4,9,5.000000,1,37,59,5
24,YssP-_6iP0SLBsqUQGs6rQ,VhvImjVs2_XE1_ig-3O-hw,4,11,5.000000,1,37,59,3
25,YssP-_6iP0SLBsqUQGs6rQ,tPeZJwKmXBj6EdxB_yfPOw,4,6,5.000000,1,37,59,2
26,YssP-_6iP0SLBsqUQGs6rQ,8wqDdfLlnT0M4PdWFh7eOg,4,5,5.000000,1,37,59,5
27,YssP-_6iP0SLBsqUQGs6rQ,wPjdB0viLu-i7YKGG3LJqA,4,99,4.000000,1,37,59,4
28,YssP-_6iP0SLBsqUQGs6rQ,gsRCdfdu6XJDG7GcTDY0wQ,4,12,5.000000,1,37,59,5
29,YssP-_6iP0SLBsqUQGs6rQ,aFlaO_MLb6YKk4oU8zmVNw,4,26,4.000000,1,37,59,4
...,...,...,...,...,...,...,...,...,...
76,IxQ1ATP_Wg_QujO9nywzcQ,0vCEI3ZJF_gXgWHpcR7WtA,4,47,3.285714,6,48,90,4
77,IxQ1ATP_Wg_QujO9nywzcQ,sYonLXU0zgZGGaRDJRPxXw,4,1,2.500000,1,48,90,1
78,IxQ1ATP_Wg_QujO9nywzcQ,88_PacBkt-EaSgW3kzimkg,4,19,3.000000,2,48,90,4
79,IxQ1ATP_Wg_QujO9nywzcQ,qnN_39P0_9d5PB21Q3gDOQ,4,76,2.500000,1,48,90,4
80,IxQ1ATP_Wg_QujO9nywzcQ,5E3eBSKdIJNjnKp-_RrQsQ,4,13,2.500000,1,48,90,3
81,IxQ1ATP_Wg_QujO9nywzcQ,Ynt9QATr3tur66_OVQNCng,4,16,2.500000,1,48,90,4
82,IxQ1ATP_Wg_QujO9nywzcQ,I2-LK2hhCqJZig-bXMAl4g,4,98,4.000000,1,48,90,4
83,IxQ1ATP_Wg_QujO9nywzcQ,ifApiOdFgQgrnFHCVnXPrQ,4,43,4.000000,1,48,90,4
84,IxQ1ATP_Wg_QujO9nywzcQ,hoThsXW1ndoytxVwc_MVLQ,4,5,4.000000,1,48,90,4
85,IxQ1ATP_Wg_QujO9nywzcQ,7dmRzwPrvtRCvDMS4RJwmw,4,14,3.000000,3,48,90,4
86,IxQ1ATP_Wg_QujO9nywzcQ,zk0SnIEa8ju2iK0mW8ccRQ,4,1,2.500000,1,48,90,2
87,IxQ1ATP_Wg_QujO9nywzcQ,zk0SnIEa8ju2iK0mW8ccRQ,4,1,2.500000,1,48,90,2
88,IxQ1ATP_Wg_QujO9nywzcQ,rwhOoAM7lfcwKufFXc8NNA,4,9,2.500000,1,48,90,4
89,IxQ1ATP_Wg_QujO9nywzcQ,6bHvullafqeGCYMoR6xlhg,4,1,2.500000,1,48,90,3
90,IxQ1ATP_Wg_QujO9nywzcQ,myEOtdBGvBhQDjkc2Tn27A,4,9,5.000000,1,48,90,4
91,IxQ1ATP_Wg_QujO9nywzcQ,yJk-iWtFhDgwWDr5tIbwIg,4,3,2.500000,1,48,90,5
92,IxQ1ATP_Wg_QujO9nywzcQ,i3TqX6Ypy774LZxENHgwWA,4,6,2.500000,1,48,90,4
93,IxQ1ATP_Wg_QujO9nywzcQ,U8GjCvF8iGizfAe_eYbqFQ,4,2,4.000000,1,48,90,5
94,IxQ1ATP_Wg_QujO9nywzcQ,9fuoK61aFGXtLhJ1DGHXyA,4,4,5.000000,1,48,90,4
95,Z-BI5HJmC2HcpiVuXwVM3A,I_47G-R2_egp7ME5u_ltew,4,6,4.000000,1,20,39,2
96,Z-BI5HJmC2HcpiVuXwVM3A,fhNxoMwwTipzjO8A9LFe8Q,4,25,4.000000,1,20,39,4
97,Z-BI5HJmC2HcpiVuXwVM3A,9OZH1Ecw-qUkCW5MS0NefA,4,1138,3.666667,6,20,39,2
98,Z-BI5HJmC2HcpiVuXwVM3A,0LzlRSXLhEsVSWFEvW_5yg,4,17,3.333333,3,20,39,3
99,Z-BI5HJmC2HcpiVuXwVM3A,o9XGClSBzCsQxbcCzTPdnQ,4,21,3.000000,2,20,39,4
100,Z-BI5HJmC2HcpiVuXwVM3A,UD7Y1CqfY6mDmRwIuCf6nA,4,955,3.300000,10,20,39,4
101,Z-BI5HJmC2HcpiVuXwVM3A,J_q8jN623uew8ZzMChXBCA,4,117,3.000000,2,20,39,4
102,Z-BI5HJmC2HcpiVuXwVM3A,oSo_3ARkzud3Wjc7evC2tg,4,29,3.000000,1,20,39,4
103,Z-BI5HJmC2HcpiVuXwVM3A,TckShYnQa0eD3WQxdoE3GQ,4,25,4.000000,1,20,39,3
104,Z-BI5HJmC2HcpiVuXwVM3A,yfRrC6MhxpIJ4-xMcrmk5Q,4,98,3.666667,3,20,39,4
105,Z-BI5HJmC2HcpiVuXwVM3A,33lGHHGU5t6Fah8G-dU0zg,4,27,4.000000,1,20,39,4

In [36]:
 final_df.shape

(90054, 8)

In [53]:
Y1 = final_df.user_rating
X1 = final_df.no_elite_reviewers
X1 = X1.reshape(len(X1), 1)
Y1 = Y1.reshape(len(Y1), 1)
clf1 = LinearRegression()
clf1 = clf1.fit(X1, Y1)
r_sqr1 = clf1.score(X1, Y1)
y_pred1 = clf1.predict(X1)
intercept1 = clf1.intercept_
coefficient1 = clf1.coef_

In [54]:
r_sqr1

0.0064775647218775489

In [55]:
#Now that we have a linear model, let's plot the line it fits on our scatterplot to get a sense of how well it fits the data:
plt.scatter(X1, Y1, color='black')
plt.plot(X1, y_pred1, color='blue', linewidth=3)

In [56]:
plt.show()

F:\PythonIDE\lib\site-packages\matplotlib\collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):